package-lock.json
package.json
src/fixtures/syntheticUnitvariantsWithLessonIds.fixture.ts
src/schema/index.ts
src/schema/syntheticUnitvariantsWithLessonIds.schema.ts
src/test/syntheticUnitvariantWithLessonIds.test.ts

A schema to work with mv_synthetic_unitvariants_with_lesson_ids_by_year

Feat/pupil 642/synthetic unitvariants with lesson ids

---

src/fixtures/index.ts

fix(unitvariantswithLessons): add export of fixture

---

src/fixtures/threadsByUnit.fixture.ts
src/schema/index.ts
src/schema/threadsByUnit.schema.ts

- add schema for response data of mv_threads_by_unit 
- add fixture for threads_by_unit

feat: add schema for threadsByUnit

---

src/fixtures/lessonContent.fixture.ts
src/fixtures/lessonData.fixture.ts
src/schema/lessonContent.schema.ts
src/schema/lessonData.schema.ts

-Adds a few missing fields for the teacher lesson query update

feat: add lesson overview missing fields

---

src/fixtures/lessonContent.fixture.ts
src/schema/lessonContent.schema.ts

- adds video_duration to lesson_content schema
- this is used on the resource cards for share

feat: add video duration to lesson content schema [LESQ-879]

---

src/schema/lessonData.schema.ts

- Adds copyright_info to copyright_content schema

fix: adds copyright info to lesson data schema

---

src/schema/lessonData.schema.ts

- amends copyright schema to accept empty object also

chore: make copyright content a union

---

src/fixtures/index.ts
src/schema/index.ts
src/schema/syntheticUnitvariantLessonsByKs.schema.ts

- exports the schema created for suv lessons by keystage

fix: export new schema

---

src/schema/lessonData.schema.ts

- reverts copyright schema to empty object

fix: remove schema change copyright content

---

src/fixtures/syntheticUnitvariantsWithLessonIds.fixture.ts
src/schema/syntheticUnitvariantsWithLessonIds.schema.ts

add lesson_sensitive_count and lesson_expired_count to the unitvariant with lesson id mv
this is key to display true lesson counts

feat(unitvariant): add sensitive and expired fields to mv schema

---

src/fixtures/unitData.fixture.ts
src/schema/unitData.schema.ts

Adding the field subjectcategories to the unitData schema

feat: add subject category field

---

src/fixtures/lessonData.fixture.ts
src/fixtures/unitData.fixture.ts
src/schema/lessonData.schema.ts
src/schema/unitData.schema.ts

add expiration_date field to lessonData and unitData schemas

feat(expiration-date): add expiration date to lesson and units

---

src/fixtures/lessonContent.fixture.ts
src/schema/base.schema.ts
src/schema/lessonContent.schema.ts

Some minor tidying up of lesson schema. (NB. requires changes in OWA and DBT before deployment)
Add the all-years and all-keystages values to the schema

feat: lesson content schema change and add all years, ks

---

src/schema/programmeFields.schema.ts

Adds subject parent to programmeFieldsSchema

feat: adds subject_parent to programeFieldsSchema

---

package.json

Empty commit to create version release
Updates semantic release config

fix: empty commit

---

src/fixtures/lessonContent.fixture.ts
src/schema/lessonContent.schema.ts

Add geo and login restrictions

feat: add login and geo restrictions

---

src/fixtures/syntheticUnitvariantLessons.fixture.ts
src/fixtures/syntheticUnitvariantLessonsByKs.fixture.ts
src/fixtures/syntheticUnitvariantsWithLessonIds.fixture.ts
src/schema/syntheticUnitvariantLessons.schema.ts
src/schema/syntheticUnitvariantLessonsByKs.schema.ts
src/schema/syntheticUnitvariantsWithLessonIds.schema.ts

NB. OWA doesn't use this anyway

feat: replace null_unitvariant with null_unitvariant_id

---

src/fixtures/index.ts
src/fixtures/syntheticUnitvariantsWithLessonIdsByKs.fixture.ts
src/fixtures/thread.fixture.ts
src/schema/index.ts
src/schema/syntheticUnitvariantsWithLessonIdsByKs.schema.ts
src/schema/thread.schema.ts
src/test/thread.test.ts

Adding threads to mv-suv-with-lesson-ids-by-ks

Feat/ctc 45/mv suv with lesson ids by ks b

---

src/fixtures/syntheticUnitvariantsWithLessonIdsByKs.fixture.ts
src/schema/syntheticUnitvariantsWithLessonIdsByKs.schema.ts

feat(uv): ad lesson ids to schema

---

src/fixtures/lessonContent.fixture.ts
src/schema/additionalFiles.schema.ts
src/schema/index.ts
src/schema/lessonContent.schema.ts

Adds additional_files to content schema

feat: add additional files to schema

---

src/fixtures/additionalFiles.fixture.ts
src/fixtures/index.ts
src/fixtures/lessonContent.fixture.ts
src/fixtures/mediaClips.fixture.ts
src/schema/actions.schema.ts
src/schema/index.ts
src/schema/lessonContent.schema.ts
src/schema/mediaClips.schema.ts

[CTC-85](https://www.notion.so/oaknationalacademy/OWA-Teacher-view-add-Files-needed-for-this-lesson-block-to-the-lesson-overview-14526cc4e1b180cc8a70cdb18b35111e) - Make additional files nullish so doens't break current overview pages
[CTC-86](https://www.notion.so/oaknationalacademy/OWA-Teacher-view-add-Lesson-file-to-Download-page-14526cc4e1b18052aa7acde1f7d961c6) - Add lessonBetaDownloads to actions query 
[CTC-121](https://www.notion.so/oaknationalacademy/I-would-like-to-view-non-fixture-media-clip-data-on-OWA-17a26cc4e1b1800da16ffcc397e47349) - Add media clip schema, fixture data

CTC-85, CTC-86, CTC-121: update owa schema

---

src/schema/syntheticUnitvariantLessons.schema.ts

DB-Tools failing a test, needs to have media_clips on the schema

feat: add media clips for db-tools pr

---

src/fixtures/lessonData.fixture.ts
src/fixtures/mediaClips.fixture.ts
src/schema/lessonData.schema.ts
src/schema/mediaClips.schema.ts
src/schema/syntheticUnitvariantLessons.schema.ts

Removes media clips from suv lessons by ks
Adds media clips to lesson data
Renames types

feat: add media clips to lesson data

---

src/schema/actions.schema.ts

Adds display_vocav_button and display_PE_title actions to schema

feat: add vocab button and pe title actions to schema

---

src/fixtures/actions.fixture.ts
src/schema/actions.schema.ts
src/schema/base.schema.ts
src/test/actions.test.ts

add GCSE CS to pathways schema

feat: add override_pathway to actions schema

---

src/fixtures/actions.fixture.ts
src/schema/actions.schema.ts

Add `is_pe_enabled` action to schema

CTC-94 Add new action to schema

---

src/fixtures/syntheticUnitvariantLessonsByKs.fixture.ts
src/fixtures/syntheticUnitvariantsWithLessonIdsByKs.fixture.ts
src/schema/index.ts
src/schema/staticLessonList.schema.ts
src/schema/syntheticUnitvariantLessons.schema.ts
src/schema/syntheticUnitvariantsWithLessonIds.schema.ts

- adds schema for static lesson list
- adds static lesson list to MVs where it will be used as a nullish field
- update fixtures

feat: add static lesson list to MV schemas

---

src/schema/syntheticProgrammesByYear.schema.ts

add features schena to subject query

feat: add features schema

---

src/schema/actions.schema.ts

Amend actions schema for swimming units

feat: amend actions schema

---

src/schema/features.schema.ts

add age_restriction feature to lesson schema

feat: add age_restriction feature to lesson schema

---

src/fixtures/lessonContent.fixture.ts
src/fixtures/lessonData.fixture.ts
src/schema/lessonContent.schema.ts
src/schema/lessonData.schema.ts

add lesson_release_date to lesson_content schema
add lesson_release_date to lesson_data schema

feat: add lesson release date to schema
